#!/bin/bash

set -e

root="$(cd "$(dirname "$0")/../../.." && pwd)"
env_dir="${root}/cf-networking-deployments/environments/${ENVIRONMENT_NAME}"
config="${env_dir}/smoke-config${CONFIG_POSTFIX}.json"

# replace admin password and secret in test config
smoke_password=${SMOKE_PASSWORD:-"$(grep cf_networking_smoke_user_password variables/variables.yml | cut -d' ' -f2)"}
echo ${smoke_password} | xargs -I{} jq '.smoke_password="{}"' "${config}" >> smoke-config/smoke-config.json
