#!/bin/bash

set -e

# replace admin password and secret in test config
VARS_STORE=${PWD}/vars-store/environments/${ENVIRONMENT_NAME}/vars-store.yml
pushd test-config/environments/${ENVIRONMENT_NAME}
  ADMIN_PASSWORD=`grep cf_admin_password ${VARS_STORE} | cut -d' ' -f2`
  sed -i -- "s/{{admin-password}}/${ADMIN_PASSWORD}/g" test-config.json
  ADMIN_SECRET=`grep uaa_admin_client_secret ${VARS_STORE} | cut -d' ' -f2`
  sed -i -- "s/{{admin-secret}}/${ADMIN_SECRET}/g" test-config.json
popd

ENVIRONMENT_PATH="test-config/environments/${ENVIRONMENT_NAME}/test-config.json"
export CONFIG=${PWD}/${CONFIG:-"${ENVIRONMENT_PATH}"}

echo $CONFIG

export NETWORK_STATS_FILE=$PWD/network-stats/stats.json

cd cf-networking
export GOPATH=$PWD

go build -o /tmp/bin/network-policy-plugin ./src/cli-plugin
cf install-plugin -f /tmp/bin/network-policy-plugin

cd src/test/acceptance
export APPS_DIR=../../example-apps
ginkgo -r -v
