#!/bin/bash

set -e -u

mkdir -p ops-files/istio-release/deploy/cf-deployment-operations
cp istio-release/deploy/cf-deployment-operations/*.yml ops-files/istio-release/deploy/cf-deployment-operations/ || true # istio-release ops files are optional

mkdir -p ops-files/cf-deployment/operations/experimental/
mkdir -p ops-files/cf-deployment/operations/backup-and-restore/
cp cf-deployment/operations/experimental/*.yml ops-files/cf-deployment/operations/experimental/
cp cf-deployment/operations/backup-and-restore/*.yml ops-files/cf-deployment/operations/backup-and-restore/
cp cf-deployment/operations/*.yml ops-files/cf-deployment/operations/

mkdir -p ops-files/cf-networking-release/manifest-generation/opsfiles
cp cf-networking-release/manifest-generation/opsfiles/*.yml ops-files/cf-networking-release/manifest-generation/opsfiles/

# old way when using cf-networking-deployments
mkdir -p ops-files/deployments-repo/environments/${ENVIRONMENT_NAME}
cp deployments-repo/environments/${ENVIRONMENT_NAME}/*.yml ops-files/deployments-repo/environments/${ENVIRONMENT_NAME}/ || true # if we don't have an env specific opsfile

# new way when using networking-oss-deployments
mkdir -p ops-files/deployments-repo/opsfiles
cp deployments-repo/deployment-helpers/opsfiles/*.yml ops-files/deployments-repo/opsfiles/ || true # if we don't have opsfiles in this location

mkdir -p ops-files/silk-release/opsfiles
cp silk-release/opsfiles/*.yml ops-files/silk-release/opsfiles/

mkdir -p ops-files/cf-networking-release/ci/opsfiles/
cp cf-networking-release/ci/opsfiles/*.yml ops-files/cf-networking-release/ci/opsfiles/

mkdir -p ops-files/cf-networking-release-ci/ci/opsfiles/
cp cf-networking-release-ci/ci/opsfiles/*.yml ops-files/cf-networking-release-ci/ci/opsfiles/
