#!/bin/sh
set -e -x

export PATH=$GOPATH/bin:$PATH

DEVELOP=$PWD/silk-dev

git clone ./silk-master ./release-merged

cd release-merged

git remote add local $DEVELOP

git fetch local
git checkout local/develop

git config --global user.email "container-networking+ci@pivotal.io"
git config --global user.name "Container Networking Bot"

git merge --no-edit release # release is the new silk-release default branch
