#!/bin/bash
# vim: set ft=sh

set -e -x

pwd

VERSION=$(cat ./netman-version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd netman-release

bosh -n create release --with-tarball --version "${VERSION}"

mkdir -p ../bosh-release
mv dev_releases/netman/*.tgz ../bosh-release/netman-${VERSION}.tgz
