#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd netman-release

bosh -n create release --with-tarball --version "${VERSION}"

mkdir -p ../tarballs
mv dev_releases/netman/*.tgz ../tarballs/netman-${VERSION}.tgz
