#!/usr/bin/env bash

set -eu

ROOT="$(cd "$(dirname $0)/../../../.." && pwd)"
. "${ROOT}/cf-networking-release-ci/ci/tasks/sli-setup/shared-sli-functions.sh"


function create_org_space() {
    cf create-org "${SLI_ORG}"
    cf create-space "${SLI_SPACE}" -o "${SLI_ORG}"
}

function bind_default_security_groups() {
  cf bind-security-group public_networks "${SLI_ORG}" --lifecycle running
  cf bind-security-group public_networks "${SLI_ORG}" --lifecycle staging
  cf bind-security-group dns "${SLI_ORG}" --lifecycle running
  cf bind-security-group dns "${SLI_ORG}" --lifecycle staging
}

function create_app() {
    if cf apps | grep "${SLI_APP_NAME}" | grep "started" > /dev/null; then
      echo "Application ${SLI_APP_NAME} already exists!"
    else
      pushd "${SLI_APP_PATH}"
      cf push "${SLI_APP_NAME}"
      popd
    fi
    if ${MAP_INTERNAL_ROUTE}; then
      map_internal_route
    fi
}

function main() {
    cf_login
    create_org_space

    cf_target

    bind_default_security_groups
    create_app
}

main
