#!/bin/bash

set -e

# replace admin password and secret in test config
ADMIN_PASSWORD="$(bosh int --path /cf_admin_password variables/variables.yml)"
sed -i -- "s/{{admin-password}}/${ADMIN_PASSWORD}/g" test-config.json
ADMIN_SECRET="$(bosh int --path /uaa_admin_client_secret variables/variables.yml)"
sed -i -- "s/{{admin-secret}}/${ADMIN_SECRET}/g" test-config.json

ENVIRONMENT_PATH="test-config/environments/${ENVIRONMENT_NAME}/test-config.json"
export CONFIG=${PWD}/${CONFIG:-"${ENVIRONMENT_PATH}"}

echo $CONFIG

export NETWORK_STATS_FILE=$PWD/network-stats/stats.json

cd cf-networking
export GOPATH=$PWD

cd src/test/acceptance
export APPS_DIR=../../example-apps
ginkgo -r -v
