#!/usr/bin/env bash

set -eu

ROOT="$(cd "$(dirname $0)/../../.." && pwd)"

# replace admin password and secret in test config
pushd "${ROOT}/test-config/environments/${ENVIRONMENT_NAME}" > /dev/null
  ADMIN_PASSWORD="$(grep '^cf_admin_password:' ${ROOT}/variables/variables.yml | cut -d" " -f2)"
  sed -i -- "s/{{admin-password}}/${ADMIN_PASSWORD}/g" test-config.json
  ADMIN_SECRET="$(grep '^uaa_admin_client_secret:' ${ROOT}/variables/variables.yml | cut -d" " -f2)"
  sed -i -- "s/{{admin-secret}}/${ADMIN_SECRET}/g" test-config.json
popd > /dev/null

ENVIRONMENT_PATH="${ROOT}/test-config/environments/${ENVIRONMENT_NAME}/test-config.json"
export CONFIG="${CONFIG:-"${ENVIRONMENT_PATH}"}"
export NETWORK_STATS_FILE="${ROOT}/network-stats/stats.json"
export GOPATH="${ROOT}/cf-networking"
export APPS_DIR="${ROOT}/cf-networking/src/example-apps"

ginkgo -r -v "${ROOT}/cf-networking/src/test/acceptance"
