#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd dev-repo

git remote add master-repo ../master-repo
git fetch master-repo

if [[ -n "$(git tag | grep -E "^${VERSION}$")" ]]; then
  echo "git tag ${VERSION} already exists. Nothing has been tagged or commited. Fast failing..."
  exit 1
fi

if [[ -n "$(git rev-list HEAD..master-repo/master)" ]]; then
  echo "Master branch contains commits not on HEAD. Nothing has been tagged or commited. Fast failing..."
  exit 1
fi
