#!/bin/bash

set -e -u

mkdir -p ops-files/istio-release/deploy/cf-deployment-operations
cp istio-release/deploy/cf-deployment-operations/*.yml ops-files/istio-release/deploy/cf-deployment-operations/ || true # istio-release ops files are optional

mkdir -p ops-files/cf-deployment/operations/experimental/
mkdir -p ops-files/cf-deployment/operations/backup-and-restore/
cp cf-deployment/operations/experimental/*.yml ops-files/cf-deployment/operations/experimental/
cp cf-deployment/operations/backup-and-restore/*.yml ops-files/cf-deployment/operations/backup-and-restore/
cp cf-deployment/operations/*.yml ops-files/cf-deployment/operations/

mkdir -p ops-files/cf-networking-release/manifest-generation/opsfiles
cp cf-networking-release/manifest-generation/opsfiles/*.yml ops-files/cf-networking-release/manifest-generation/opsfiles/

mkdir -p ops-files/deployments-repo/environments/${ENVIRONMENT_NAME}
mkdir -p ops-files/deployments-repo/operations
cp deployments-repo/smaller-footprint.yml ops-files/deployments-repo/
cp deployments-repo/operations/*.yml ops-files/deployments-repo/operations/ || true # only cf-networking-deployment has these
cp deployments-repo/environments/${ENVIRONMENT_NAME}/*.yml ops-files/deployments-repo/environments/${ENVIRONMENT_NAME}/ || true # if we don't have an env specific opsfile

mkdir -p ops-files/silk-release/opsfiles
cp silk-release/opsfiles/*.yml ops-files/silk-release/opsfiles/

mkdir -p ops-files/cf-networking-release/ci/opsfiles/
cp cf-networking-release/ci/opsfiles/*.yml ops-files/cf-networking-release/ci/opsfiles/
