#!/bin/bash

set -e -u

cp istio-release/deploy/cf-deployment-operations/*.yml ops-files/ || true # istio-release ops files are optional

cp cf-deployment/operations/**/*.yml ops-files/
cp cf-deployment/operations/*.yml ops-files/

cp cf-networking-release/manifest-generation/opsfiles/*.yml ops-files/

cp deployments-repo/smaller-footprint.yml ops-files/
cp deployments-repo/environments/${ENVIRONMENT_NAME}/opsfile*.yml ops-files/ || true # if we don't have an env specific opsfile

cp silk-release/opsfiles/*.yml ops-files/

cp cf-networking-release-ci/ci/opsfiles/*.yml ops-files/
