#!/bin/bash

set -eu

VERSION=$(cat ./${VERSION_NAME}/number)

pushd my-release > /dev/null
  bosh create-release --tarball=../tarballs/${RELEASE_NAME}-${VERSION}.tgz --name $RELEASE_NAME --timestamp-version
popd > /dev/null
