#!/bin/bash

set -e

curl -o ./gcloud-cli.tar.gz  https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-223.0.0-linux-x86_64.tar.gz
echo "9b7492f593d35de06bee72a5a25d469bf72e880001f76d2a55e8d680f6e084df  ./gcloud-cli.tar.gz" | shasum -c

tar zxvf ./gcloud-cli.tar.gz google-cloud-sdk
yes n | ./google-cloud-sdk/install.sh
export PATH=$PATH:$PWD/google-cloud-sdk/bin

(echo "nameserver 8.8.8.8" && cat /etc/resolv.conf) > /tmp/new_resolv.conf
cat /tmp/new_resolv.conf > /etc/resolv.conf

gcloud config set project "${PROJECT_ID}"

gcloud --quiet auth activate-service-account --key-file "deployments-repo/environments/${ENVIRONMENT_NAME}/restore-database-service-account.json"

gcloud --quiet sql backups restore "${BACKUP_ID}" --async --restore-instance "${DATABASE_NAME}"
