#!/bin/bash -eu

curl -L https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.1.0/bbr-1.1.0.tar \
   --output /tmp/bbr.tar && tar -xvf /tmp/bbr.tar -C /tmp

export GOPATH=${PWD}/go
export PATH=$GOPATH/bin:$PATH

# install dep because drats doesn't
curl -L -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 && chmod +x /usr/local/bin/dep

curl -L -o /usr/local/bin/bosh-cli https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.17-linux-amd64 && chmod +x /usr/local/bin/bosh-cli

pushd deployments-repo/environments/$ENVIRONMENT_NAME > /dev/null
  export CF_DEPLOYMENT_NAME="${ENVIRONMENT_NAME}.c2c.cf-app.com"
  export CF_API_URL="https://api.${ENVIRONMENT_NAME}.c2c.cf-app.com"
  export CF_ADMIN_USERNAME="admin"
  export CF_ADMIN_PASSWORD=$(grep cf_admin_password vars-store.yml  | cut -d ' ' -f2)
  export BOSH_ENVIRONMENT=$(bbl director-address)

  export BOSH_CLIENT_SECRET=$(bbl director-password)
  export BOSH_CLIENT=$(bbl director-username)
  bbl director-ca-cert > /tmp/ca.crt
  export BOSH_CERT_PATH=/tmp/ca.crt
  export BBR_BUILD_PATH=/tmp/releases/bbr
  export FOCUSED_SUITE_NAME="cf-networking"
popd

pushd $GOPATH/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests > /dev/null
  ./scripts/_run_acceptance_tests.sh
popd
