#!/usr/bin/env bash

set -eo pipefail

pushd "${PWD}/bbl-state/environments/${ENVIRONMENT}" > /dev/null
  eval "$(bbl print-env)"
  export BOSH_DEPLOYMENT="cf"
  cf_admin_password=$(credhub find -j -n cf_admin_password | jq -r .credentials[].name | xargs credhub get -j -n | jq -r .value)
popd > /dev/null

gopath_dir="/root/go/src/code.cloudfoundry.org"
mkdir -p "${gopath_dir}"
cp -R istio-scaling "${gopath_dir}"

go install code.cloudfoundry.org/istio-scaling/vendor/github.com/onsi/ginkgo/ginkgo

pushd "${gopath_dir}/istio-scaling"
cat << EOF > "${PWD}/config.json"
{
  "cf_admin_user": "admin",
  "cf_admin_password": "$cf_admin_password",
  "cf_internal_apps_domain": "apps.internal",
  "cf_system_domain": "${ENVIRONMENT}.c2c.cf-app.com",
  "cf_istio_domain": "istio.${ENVIRONMENT}.c2c.cf-app.com",
  "cf_org_name": "scaling-test-org",
  "cf_space_name": "scaling-test-space"
}
EOF
cat << EOF > "${PWD}/plan.json"
{
  "number_of_apps_to_push": $NUMBER_OF_APPS,
  "number_of_apps_to_curl": $NUMBER_OF_APPS,
  "app_instances": 1,
  "cleanup": $CLEANUP_ORG
}
EOF

  CONFIG="$PWD/config.json" PLAN="$PWD/plan.json" scripts/test
popd
