#!/bin/bash -eu

curl -L https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.1.0/bbr-1.1.0.tar \
   --output /tmp/bbr.tar && tar -xvf /tmp/bbr.tar -C /tmp

export GOPATH=${PWD}/go
export PATH=$GOPATH/bin:$PATH

export CF_VARS_STORE_PATH="vars-store.yml"
export BBR_BUILD_PATH=/tmp/releases/bbr
export FOCUSED_SUITE_NAME="cf-networking"

# install dep because drats doesn't
curl -L -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 && chmod +x /usr/local/bin/dep

curl -L -o /usr/local/bin/bosh-cli https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.17-linux-amd64 && chmod +x /usr/local/bin/bosh-cli

pushd $GOPATH/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests > /dev/null
  ./scripts/run_acceptance_tests_with_bbl_env.sh deployments-repo/environments/${ENVIRONMENT_NAME}
popd
