#!/bin/bash

set -e

root="$(cd "$(dirname "$0")/../../.." && pwd)"
env_dir="${root}/cf-networking-deployments/environments/${ENVIRONMENT_NAME}"
config="${env_dir}/smoke-config.json"

bosh int "${config}" --vars-file "${env_dir}/vars-store.yml" > smoke-config/smoke-config.json