#!/bin/bash

set -e

ROOT="$(cd "$(dirname $0)/../../.." && pwd)"

export CONFIG="${ROOT}/${CONFIG:-"test-config/environments/${ENVIRONMENT_NAME}/smoke-config.json"}"
export GOPATH="${ROOT}/cf-networking"
export APPS_DIR="${ROOT}/cf-networking/src/example-apps"

function main() {
  local exit_status

  interpolate_smoke_password

  echo "${CONFIG}"
  pushd "${ROOT}/cf-networking/src/test/smoke-sd" > /dev/null
    # Push App Smoke
    set +e
    ginkgo -r -v --focus="Push App Smoke"
    exit_status="$?"
    set -e

    report_smoke_metric_to_datadog "cf-app-sd-smoke.ResolveAddSuccess" "${exit_status}"

    if [[ "${exit_status}" -ne 0 ]]; then
      exit "${exit_status}"
    fi

    # Delete App Smoke
    set +e
    ginkgo -r -v --focus="Delete App Smoke"
    exit_status="$?"
    set -e

    report_smoke_metric_to_datadog "cf-app-sd-smoke.ResolveDeleteSuccess" "${exit_status}"
    exit "${exit_status}"
  popd > /dev/null
}

function report_smoke_metric_to_datadog() {
  local metric="${1}"
  local exit_status="${2}"
  local current_time
  current_time="$(date +%s)"

  curl -X POST -H "Content-type: application/json" \
    -d "{ \"series\" :
           [{\"metric\":\"${metric}\",
            \"points\":[[${current_time}, ${exit_status}]],
            \"type\":\"gauge\",
            \"tags\":[\"deployment:${ENVIRONMENT_TAG}\"]
          }]
        }" \
  "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}"
}

function interpolate_smoke_password() {
  # replace admin password and secret in test config
  pushd "${ROOT}/test-config/environments/${ENVIRONMENT_NAME}" > /dev/null
    local smoke_password
    smoke_password="$(grep cf_networking_smoke_user_password vars-store.yml  | cut -d' ' -f2)"
    sed -i -- "s/{{smoke-password}}/${smoke_password}/g" smoke-config.json
  popd > /dev/null
}

main
