#!/usr/bin/env bash

set -eu

export GOPATH=$PWD/cf-networking
export PATH="${GOPATH}/bin":$PATH
export APPS_DIR=$PWD/cf-networking/src/example-apps

go install github.com/onsi/ginkgo/ginkgo

# replace admin password and secret in test config
pushd "test-config/environments/${ENVIRONMENT_NAME}" > /dev/null
  ADMIN_PASSWORD="$(bosh int --path /cf_admin_password variables/variables.yml)"
  sed -i -- "s/{{admin-password}}/${ADMIN_PASSWORD}/g" test-config.json
  ADMIN_SECRET="$(bosh int --path /uaa_admin_client_secret variables/variables.yml)"
  sed -i -- "s/{{admin-secret}}/${ADMIN_SECRET}/g" test-config.json
popd > /dev/null

ENVIRONMENT_PATH="test-config/environments/${ENVIRONMENT_NAME}/test-config.json"
export CONFIG=${PWD}/${CONFIG:-"${ENVIRONMENT_PATH}"}


pushd $GOPATH/src/test/acceptance-sd
    ginkgo -keepGoing -randomizeAllSpecs -randomizeSuites -race .
popd
