#!/bin/bash

set -euo pipefail

function cleanup() {
  pkill ssh || true
}

trap 'cleanup' EXIT

# Targetting director
pushd "deployments-repo/environments/$ENVIRONMENT_NAME"
  eval "$(bbl print-env)"
popd

export GOPATH=$PWD/cf-networking
export PATH="${GOPATH}/bin":$PATH

go install github.com/onsi/ginkgo/ginkgo

export CONFIG="$PWD/deployments-repo/environments/$ENVIRONMENT_NAME/perf-config.json"

pushd cf-networking/src/test/performance-sd
   ginkgo -race deploy/
   bosh -d performance run-errand performance-test-sd --keep-alive
   bosh -n -d performance delete-deployment
popd
