#!/bin/bash

set -euo pipefail

function cleanup() {
  pkill ssh || true
}

trap 'cleanup' EXIT

# set bosh target
function setup_bosh_env_vars() {
  pushd "env-repo/${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
}

setup_bosh_env_vars

runtime_config="runtime-config/${RUNTIME_CONFIG_FILE}"
vars_store="vars-store/${VARS_STORE_FILE}"

bosh update-runtime-config -n --vars-store "$vars_store" "$runtime_config"
