#!/usr/bin/env bash

set -u

ROOT="$(cd "$(dirname $0)/../../.." && pwd)"

ADMIN_PASSWORD="$(grep '^cf_admin_password:' ${ROOT}/variables/variables.yml | cut -d" " -f2)"

# try 10 times dumbly
for i in `seq 0 9`
do
  echo "try #$i"
  cf api "api.${SYSTEM_DOMAIN}" --skip-ssl-validation
  cf auth admin "${ADMIN_PASSWORD}"
done


