// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/policy-server/api"
	"code.cloudfoundry.org/policy-server/store"
)

type AsgMapper struct {
	AsBytesStub        func([]store.SecurityGroup, store.Pagination) ([]byte, error)
	asBytesMutex       sync.RWMutex
	asBytesArgsForCall []struct {
		arg1 []store.SecurityGroup
		arg2 store.Pagination
	}
	asBytesReturns struct {
		result1 []byte
		result2 error
	}
	asBytesReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AsgMapper) AsBytes(arg1 []store.SecurityGroup, arg2 store.Pagination) ([]byte, error) {
	var arg1Copy []store.SecurityGroup
	if arg1 != nil {
		arg1Copy = make([]store.SecurityGroup, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.asBytesMutex.Lock()
	ret, specificReturn := fake.asBytesReturnsOnCall[len(fake.asBytesArgsForCall)]
	fake.asBytesArgsForCall = append(fake.asBytesArgsForCall, struct {
		arg1 []store.SecurityGroup
		arg2 store.Pagination
	}{arg1Copy, arg2})
	stub := fake.AsBytesStub
	fakeReturns := fake.asBytesReturns
	fake.recordInvocation("AsBytes", []interface{}{arg1Copy, arg2})
	fake.asBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AsgMapper) AsBytesCallCount() int {
	fake.asBytesMutex.RLock()
	defer fake.asBytesMutex.RUnlock()
	return len(fake.asBytesArgsForCall)
}

func (fake *AsgMapper) AsBytesCalls(stub func([]store.SecurityGroup, store.Pagination) ([]byte, error)) {
	fake.asBytesMutex.Lock()
	defer fake.asBytesMutex.Unlock()
	fake.AsBytesStub = stub
}

func (fake *AsgMapper) AsBytesArgsForCall(i int) ([]store.SecurityGroup, store.Pagination) {
	fake.asBytesMutex.RLock()
	defer fake.asBytesMutex.RUnlock()
	argsForCall := fake.asBytesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AsgMapper) AsBytesReturns(result1 []byte, result2 error) {
	fake.asBytesMutex.Lock()
	defer fake.asBytesMutex.Unlock()
	fake.AsBytesStub = nil
	fake.asBytesReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *AsgMapper) AsBytesReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.asBytesMutex.Lock()
	defer fake.asBytesMutex.Unlock()
	fake.AsBytesStub = nil
	if fake.asBytesReturnsOnCall == nil {
		fake.asBytesReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.asBytesReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *AsgMapper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.asBytesMutex.RLock()
	defer fake.asBytesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AsgMapper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.AsgMapper = new(AsgMapper)
