#!/bin/bash

set -exuo pipefail

ROOT=${PWD}
RELEASE_TARBALL_PATH=${ROOT}/release.tgz
DATE=$(date '+%Y-%m-%d %H:%M:%S')
pushd release
  bosh create-release --tarball="${RELEASE_TARBALL_PATH}"
  mkdir -p docs
  version=$(tar -Oxz packages/golang-1-linux.tgz < "${RELEASE_TARBALL_PATH}" | tar z --list | grep -ohE 'go[0-9]\.[0-9]{1,2}\.[0-9]{0,2}')
  echo "This file was updated by CI on ${DATE}" > docs/go.version
  echo "$version" >> docs/go.version

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"

  git checkout "${BRANCH}"

  if [[ -n $(git status --porcelain) ]]; then
    echo "changes detected, will commit..."
    git add --all
    git commit -m "Update Go version file to ${version}"

    git log -1 --color | cat
  else
   echo "no changes in repo, no commit necessary"
  fi
popd


shopt -s dotglob
cp -R release/* modified-release/

