#!/bin/bash

set -e -u
set -o pipefail

# replace admin password in test config
ADMIN_PASSWORD=`grep cf_admin_password variables/variables.yml  | cut -d' ' -f2`
sed -i -- "s/{{admin-password}}/${ADMIN_PASSWORD}/g" cf-networking-deployments/environments/${ENVIRONMENT}/integration_config.json

cp cf-networking-deployments/environments/${ENVIRONMENT}/integration_config.json integration-config/
