#!/usr/bin/env bash

set -eu

ROOT="$(cd "$(dirname $0)/../../../.." && pwd)"

export CONFIG="${CONFIG:-"${ROOT}/test-config/test-config.json"}"
export NETWORK_STATS_FILE="${ROOT}/network-stats/stats.json"
export RELEASE_DIR="${ROOT}/cf-networking"
export APPS_DIR="${ROOT}/cf-networking/src/example-apps"

BIN_DIR="${RELEASE_DIR}/bin"
mkdir -p "${BIN_DIR}"
export PATH="${BIN_DIR}:${PATH}"

pushd "${RELEASE_DIR}/src/code.cloudfoundry.org"
    go build -o "${BIN_DIR}/ginkgo" github.com/onsi/ginkgo/ginkgo
    ginkgo -v -keepGoing -randomizeAllSpecs -randomizeSuites -race "test/${TEST_NAME}"
popd
