// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"policy-server/store/migrations"
	"sync"

	migrate "github.com/rubenv/sql-migrate"
)

type MigrateExecutor struct {
	ExecStub        func(db migrations.MigrationDb, dialect string, m migrate.MigrationSource, dir migrate.MigrationDirection) (int, error)
	execMutex       sync.RWMutex
	execArgsForCall []struct {
		db      migrations.MigrationDb
		dialect string
		m       migrate.MigrationSource
		dir     migrate.MigrationDirection
	}
	execReturns struct {
		result1 int
		result2 error
	}
	execReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MigrateExecutor) Exec(db migrations.MigrationDb, dialect string, m migrate.MigrationSource, dir migrate.MigrationDirection) (int, error) {
	fake.execMutex.Lock()
	ret, specificReturn := fake.execReturnsOnCall[len(fake.execArgsForCall)]
	fake.execArgsForCall = append(fake.execArgsForCall, struct {
		db      migrations.MigrationDb
		dialect string
		m       migrate.MigrationSource
		dir     migrate.MigrationDirection
	}{db, dialect, m, dir})
	fake.recordInvocation("Exec", []interface{}{db, dialect, m, dir})
	fake.execMutex.Unlock()
	if fake.ExecStub != nil {
		return fake.ExecStub(db, dialect, m, dir)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.execReturns.result1, fake.execReturns.result2
}

func (fake *MigrateExecutor) ExecCallCount() int {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return len(fake.execArgsForCall)
}

func (fake *MigrateExecutor) ExecArgsForCall(i int) (migrations.MigrationDb, string, migrate.MigrationSource, migrate.MigrationDirection) {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return fake.execArgsForCall[i].db, fake.execArgsForCall[i].dialect, fake.execArgsForCall[i].m, fake.execArgsForCall[i].dir
}

func (fake *MigrateExecutor) ExecReturns(result1 int, result2 error) {
	fake.ExecStub = nil
	fake.execReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *MigrateExecutor) ExecReturnsOnCall(i int, result1 int, result2 error) {
	fake.ExecStub = nil
	if fake.execReturnsOnCall == nil {
		fake.execReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.execReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *MigrateExecutor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MigrateExecutor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migrations.MigrateExecutor = new(MigrateExecutor)
