#!/bin/bash

set -e -u
set -o pipefail

pushd $SOURCE_DIR > /dev/null
  if [ "${PRE_RELEASE}" = "true" ]; then
    #ship-wot (new tag does not exist yet)
    old_version=$(git tag --sort=version:refname | egrep "^\d+\.\d+\.\d+$" | tail -1)
    new_version=$(git rev-parse HEAD)
  else
    #ship-it (new tag has been created)
    old_version=$(git tag --sort=version:refname | egrep "^\d+\.\d+\.\d+$" | tail -2 | head -1)
    new_version=$(git tag --sort=version:refname | egrep "^\d+\.\d+\.\d+$" | tail -1)
  fi

  diff_string="$old_version..$new_version"
  echo "comparing $diff_string:"
  git --no-pager diff $diff_string jobs/*/spec
popd > /dev/null
