#!/usr/bin/env bash

set -eu

ROOT="$(cd "$(dirname $0)/../../../.." && pwd)"
. "${ROOT}/cf-networking-release-ci/ci/tasks/sli-setup/shared-sli-functions.sh"

APP_URL="${SLI_APP_NAME}.$(get_var_from_json apps_domain)"

function time_dig_internal_route() {
  curl --silent --fail "${APP_URL}"/timed_dig/"${SLI_APP_NAME}".apps.internal | jq -e .lookup_time_ms
}

function report_timing_to_datadog() {
    local time_to_resolve="${1}"

    curl -f -X POST -H "Content-type: application/json" \
    -d "{ \"series\" :
           [{\"metric\":\"cf_networking_sli.ResolveRouteTime\",
            \"points\":[[$(date +%s), ${time_to_resolve}]],
            \"type\":\"gauge\",
            \"tags\":[\"deployment:${ENVIRONMENT_TAG}\"]
          }]
        }" \
      "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}"
}

function report_status_to_datadog() {
    local time_to_resolve="${1}"
    local time_threshold="${2}"
    local status=0

    if [[ ${time_to_resolve} -le ${time_threshold} ]]; then
      status=1
    fi

    curl -f -X POST -H "Content-type: application/json" \
    -d "{ \"series\" :
           [{\"metric\":\"cf_networking_sli.ResolveRoute${time_threshold}msStatus\",
            \"points\":[[$(date +%s), ${status}]],
            \"type\":\"gauge\",
            \"tags\":[\"deployment:${ENVIRONMENT_TAG}\"]
          }]
        }" \
      "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}"
}

function main() {
    cf_login
    cf_target

    local time_to_resolve=$(time_dig_internal_route)

    printf "Time to resolve route: ${time_to_resolve}\n"
    report_timing_to_datadog "${time_to_resolve}"
    report_status_to_datadog "${time_to_resolve}" "15"
    report_status_to_datadog "${time_to_resolve}" "200"
}

main
