#!/bin/bash

set -e -u

THIS_DIR=$(cd $(dirname $0) && pwd)
cd $THIS_DIR

export CONFIG=/tmp/bosh-lite-integration-config.json
export APPS_DIR=${GOPATH}/src/example-apps

echo '
{
  "api": "api.bosh-lite.com",
  "admin_user": "admin",
  "admin_password": "admin",
  "apps_domain": "bosh-lite.com",
  "skip_ssl_validation": true,
  "test_app_instances": 2,
  "test_applications": 4,
  "concurrency": 4
}
' > $CONFIG

go run ../cmd/cf-pusher/main.go --config $CONFIG
