#!/bin/bash

set -e -u
set -o pipefail

environment_path="${PWD}/test-config/environments/${ENVIRONMENT_NAME}"
export CONFIG=$environment_path/test-config.json

export NETWORK_STATS_FILE=$PWD/network-stats/stats.json

cd cf-networking
export GOPATH=$PWD

cd src/test/scaling
ginkgo -v
