#!/bin/bash

set -e -u
set -o pipefail

environment_path="${PWD}/test-config/${TEST_CONFIG_DIR}"
export CONFIG=$environment_path/scaling-test-config.json

export NETWORK_STATS_FILE=$PWD/network-stats/stats.json

cd cf-networking/src/code.cloudfoundry.org

ginkgo -v test/scaling
