// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"policy-server/store"
	"sync"
)

type EgressPolicyStore struct {
	AllWithTxStub        func() ([]store.EgressPolicy, error)
	allWithTxMutex       sync.RWMutex
	allWithTxArgsForCall []struct{}
	allWithTxReturns     struct {
		result1 []store.EgressPolicy
		result2 error
	}
	allWithTxReturnsOnCall map[int]struct {
		result1 []store.EgressPolicy
		result2 error
	}
	ByGuidsWithTxStub        func(ids []string) ([]store.EgressPolicy, error)
	byGuidsWithTxMutex       sync.RWMutex
	byGuidsWithTxArgsForCall []struct {
		ids []string
	}
	byGuidsWithTxReturns struct {
		result1 []store.EgressPolicy
		result2 error
	}
	byGuidsWithTxReturnsOnCall map[int]struct {
		result1 []store.EgressPolicy
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *EgressPolicyStore) AllWithTx() ([]store.EgressPolicy, error) {
	fake.allWithTxMutex.Lock()
	ret, specificReturn := fake.allWithTxReturnsOnCall[len(fake.allWithTxArgsForCall)]
	fake.allWithTxArgsForCall = append(fake.allWithTxArgsForCall, struct{}{})
	fake.recordInvocation("AllWithTx", []interface{}{})
	fake.allWithTxMutex.Unlock()
	if fake.AllWithTxStub != nil {
		return fake.AllWithTxStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.allWithTxReturns.result1, fake.allWithTxReturns.result2
}

func (fake *EgressPolicyStore) AllWithTxCallCount() int {
	fake.allWithTxMutex.RLock()
	defer fake.allWithTxMutex.RUnlock()
	return len(fake.allWithTxArgsForCall)
}

func (fake *EgressPolicyStore) AllWithTxReturns(result1 []store.EgressPolicy, result2 error) {
	fake.AllWithTxStub = nil
	fake.allWithTxReturns = struct {
		result1 []store.EgressPolicy
		result2 error
	}{result1, result2}
}

func (fake *EgressPolicyStore) AllWithTxReturnsOnCall(i int, result1 []store.EgressPolicy, result2 error) {
	fake.AllWithTxStub = nil
	if fake.allWithTxReturnsOnCall == nil {
		fake.allWithTxReturnsOnCall = make(map[int]struct {
			result1 []store.EgressPolicy
			result2 error
		})
	}
	fake.allWithTxReturnsOnCall[i] = struct {
		result1 []store.EgressPolicy
		result2 error
	}{result1, result2}
}

func (fake *EgressPolicyStore) ByGuidsWithTx(ids []string) ([]store.EgressPolicy, error) {
	var idsCopy []string
	if ids != nil {
		idsCopy = make([]string, len(ids))
		copy(idsCopy, ids)
	}
	fake.byGuidsWithTxMutex.Lock()
	ret, specificReturn := fake.byGuidsWithTxReturnsOnCall[len(fake.byGuidsWithTxArgsForCall)]
	fake.byGuidsWithTxArgsForCall = append(fake.byGuidsWithTxArgsForCall, struct {
		ids []string
	}{idsCopy})
	fake.recordInvocation("ByGuidsWithTx", []interface{}{idsCopy})
	fake.byGuidsWithTxMutex.Unlock()
	if fake.ByGuidsWithTxStub != nil {
		return fake.ByGuidsWithTxStub(ids)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.byGuidsWithTxReturns.result1, fake.byGuidsWithTxReturns.result2
}

func (fake *EgressPolicyStore) ByGuidsWithTxCallCount() int {
	fake.byGuidsWithTxMutex.RLock()
	defer fake.byGuidsWithTxMutex.RUnlock()
	return len(fake.byGuidsWithTxArgsForCall)
}

func (fake *EgressPolicyStore) ByGuidsWithTxArgsForCall(i int) []string {
	fake.byGuidsWithTxMutex.RLock()
	defer fake.byGuidsWithTxMutex.RUnlock()
	return fake.byGuidsWithTxArgsForCall[i].ids
}

func (fake *EgressPolicyStore) ByGuidsWithTxReturns(result1 []store.EgressPolicy, result2 error) {
	fake.ByGuidsWithTxStub = nil
	fake.byGuidsWithTxReturns = struct {
		result1 []store.EgressPolicy
		result2 error
	}{result1, result2}
}

func (fake *EgressPolicyStore) ByGuidsWithTxReturnsOnCall(i int, result1 []store.EgressPolicy, result2 error) {
	fake.ByGuidsWithTxStub = nil
	if fake.byGuidsWithTxReturnsOnCall == nil {
		fake.byGuidsWithTxReturnsOnCall = make(map[int]struct {
			result1 []store.EgressPolicy
			result2 error
		})
	}
	fake.byGuidsWithTxReturnsOnCall[i] = struct {
		result1 []store.EgressPolicy
		result2 error
	}{result1, result2}
}

func (fake *EgressPolicyStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.allWithTxMutex.RLock()
	defer fake.allWithTxMutex.RUnlock()
	fake.byGuidsWithTxMutex.RLock()
	defer fake.byGuidsWithTxMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *EgressPolicyStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
