#!/bin/bash
set -e -u

ROOT_DIR_PATH="$(cd $(dirname $0)/.. && pwd)"
cd "${ROOT_DIR_PATH}"

db=${DB:-"postgres"} # if not set, default to postgres

if [ "$db" = "mysql" ]; then
  docker_image=c2cnetworking/dev-mysql
elif [ "$db" = "mysql8" ]; then
  docker_image=c2cnetworking/dev-mysql8
else
  docker_image=c2cnetworking/dev-postgres-ifb
fi

docker run \
   --rm \
   -it \
   --privileged \
   -v "${PWD}:/cf-networking-release" \
   -e "DB=$db" \
   --cap-add ALL \
   -w /cf-networking-release \
   $docker_image \
   /bin/bash "$@"
