#!/bin/bash
set -e -u

ROOT_DIR_PATH="$(cd $(dirname $0)/.. && pwd)"
cd ${ROOT_DIR_PATH}

db=${DB:-"postgres"} # if not set, default to postgres

kernelversion="$(docker run -t -i alpine:latest uname -r | tr -d '\r\n' | tr -d '\-moby')"
if [ $db = "mysql" ]; then
  # pinning back because we don't support mysql 8
  docker_image=c2cnetworking/dev-mysql:0.18.0
else
  docker_image=c2cnetworking/dev-postgres-ifb
fi

docker run \
   --rm \
   -it \
   --privileged \
   -v ${PWD}:/cf-networking-release \
   -e GOPATH=/cf-networking-release \
   -e DB=$db \
   --cap-add ALL \
   -w / \
   $docker_image \
   /bin/bash "$@"
