#!/bin/bash
set -e -u

ROOT_DIR_PATH="$(cd $(dirname $0)/.. && pwd)"
cd ${ROOT_DIR_PATH}

db=${DB:-"postgres"} # if not set, default to postgres

kernelversion="4.9.36"
docker_image=c2cnetworking/dev-$db
if [ $db = "none" ] || [ $db = "postgres" ]; then
  docker_image=c2cnetworking/dev-postgres-ifb:$kernelversion
fi

docker run \
   --rm \
   -it \
   --privileged \
   -v ${PWD}:/cf-networking-release \
   -e GOPATH=/cf-networking-release \
   -e DB=$db \
   --cap-add ALL \
   -w / \
   $docker_image \
   /bin/bash "$@"
