#!/bin/bash
set -e -u

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

if [ ${MYSQL:-"false"} = "true" ]; then
  docker run --privileged \
     --rm \
     -v $PWD:/cf-networking \
     -e GOPATH=/cf-networking \
     -e NO_DB="${NO_DB:-""}" \
     -e MYSQL=true \
     -w / \
     c2cnetworking/dev-mysql \
     /cf-networking/ci/unit-and-integration-tests.sh "$@"
else
  docker run --privileged \
     --rm \
     -v $PWD:/cf-networking \
     -e GOPATH=/cf-networking \
     -e NO_DB="${NO_DB:-""}" \
     -w / \
     c2cnetworking/dev-postgres \
     /cf-networking/ci/unit-and-integration-tests.sh "$@"
fi
