#!/bin/bash
set -e -u

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

if [ ${MYSQL:-"false"} = "true" ]; then
  docker pull c2cnetworking/dev-mysql
  docker run --privileged \
     --rm \
     -v $PWD:/netman-release \
     -e GOPATH=/netman-release \
     -e GINKGO_EXTRA_FLAGS="${GINKGO_EXTRA_FLAGS:-""}" \
     -e NO_DB="${NO_DB:-""}" \
     -e MYSQL=true \
     -w / \
     c2cnetworking/dev-mysql \
     /netman-release/ci/netman-tests.sh "$@"
else
  docker pull c2cnetworking/dev-postgres
  docker run --privileged \
     --rm \
     -v $PWD:/netman-release \
     -e GOPATH=/netman-release \
     -e GINKGO_EXTRA_FLAGS="${GINKGO_EXTRA_FLAGS:-""}" \
     -e NO_DB="${NO_DB:-""}" \
     -w / \
     c2cnetworking/dev-postgres \
     /netman-release/ci/netman-tests.sh "$@"
fi
