#!/bin/sh

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="cf-networking-certs"
mkdir -p ${depot_path}

# CA to distribute to cf-networking policy server and client
certstrap --depot-path ${depot_path} init --passphrase '' --common-name cf-networking-ca

# Server certificate for the policy server
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name policy-server.service.cf.internal --domain '*.policy-server.service.cf.internal,policy-server.service.cf.internal'
certstrap --depot-path ${depot_path} sign policy-server.service.cf.internal --CA cf-networking-ca
mv -f ${depot_path}/policy-server.service.cf.internal.key ${depot_path}/policy_server.key
mv -f ${depot_path}/policy-server.service.cf.internal.csr ${depot_path}/policy_server.csr
mv -f ${depot_path}/policy-server.service.cf.internal.crt ${depot_path}/policy_server.crt

# Client certificate for the policy agent
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name 'policy-agent'
certstrap --depot-path ${depot_path} sign policy-agent --CA cf-networking-ca
mv -f ${depot_path}/policy-agent.key ${depot_path}/policy_client.key
mv -f ${depot_path}/policy-agent.csr ${depot_path}/policy_client.csr
mv -f ${depot_path}/policy-agent.crt ${depot_path}/policy_client.crt


# Server certificate for the connectivity server
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name connectivity-server.service.cf.internal --domain '*.connectivity-server.service.cf.internal,connectivity-server.service.cf.internal'
certstrap --depot-path ${depot_path} sign connectivity-server.service.cf.internal --CA cf-networking-ca
mv -f ${depot_path}/connectivity-server.service.cf.internal.key ${depot_path}/connectivity_server.key
mv -f ${depot_path}/connectivity-server.service.cf.internal.csr ${depot_path}/connectivity_server.csr
mv -f ${depot_path}/connectivity-server.service.cf.internal.crt ${depot_path}/connectivity_server.crt

# Client certificate for the connectivity agent
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name 'connectivity-agent'
certstrap --depot-path ${depot_path} sign connectivity-agent --CA cf-networking-ca
mv -f ${depot_path}/connectivity-agent.key ${depot_path}/connectivity_client.key
mv -f ${depot_path}/connectivity-agent.csr ${depot_path}/connectivity_client.csr
mv -f ${depot_path}/connectivity-agent.crt ${depot_path}/connectivity_client.crt
