#!/bin/sh

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="cf-networking-certs"
mkdir -p ${depot_path}

# CA to distribute to cf-networking clients and servers
certstrap --depot-path ${depot_path} init --passphrase '' --common-name cf-networking-ca

# Server certificate for the policy server
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name policy-server.service.cf.internal --domain '*.policy-server.service.cf.internal,policy-server.service.cf.internal'
certstrap --depot-path ${depot_path} sign policy-server.service.cf.internal --CA cf-networking-ca
mv -f ${depot_path}/policy-server.service.cf.internal.key ${depot_path}/server.key
mv -f ${depot_path}/policy-server.service.cf.internal.csr ${depot_path}/server.csr
mv -f ${depot_path}/policy-server.service.cf.internal.crt ${depot_path}/server.crt

# Client certificate for the policy agents
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name 'policy-agent'
certstrap --depot-path ${depot_path} sign policy-agent --CA cf-networking-ca
mv -f ${depot_path}/policy-agent.key ${depot_path}/client.key
mv -f ${depot_path}/policy-agent.csr ${depot_path}/client.csr
mv -f ${depot_path}/policy-agent.crt ${depot_path}/client.crt
