#!/bin/sh

set -e -x

REPO_ROOT="$(dirname $0)/.."

# Install certstrap
go install github.com/square/certstrap@latest

# Place keys and certificates here
depot_path="${REPO_ROOT}/src/code.cloudfoundry.org/policy-server/integration/fixtures"
mkdir -p ${depot_path}

# CA to distribute to cf-networking policy server and client
certstrap --depot-path ${depot_path} init --passphrase '' --common-name netman-ca

# Server certificate for the policy server
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name policy-server.service.cf.internal --domain '*.policy-server.service.cf.internal,policy-server.service.cf.internal' --ip 127.0.0.1
certstrap --depot-path ${depot_path} sign policy-server.service.cf.internal --CA netman-ca
mv -f ${depot_path}/policy-server.service.cf.internal.key ${depot_path}/server.key
mv -f ${depot_path}/policy-server.service.cf.internal.crt ${depot_path}/server.crt

# Client certificate for the policy agent
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name 'policy-agent'
certstrap --depot-path ${depot_path} sign policy-agent --CA netman-ca
mv -f ${depot_path}/policy-agent.key ${depot_path}/client.key
mv -f ${depot_path}/policy-agent.crt ${depot_path}/client.crt

rm -f "${depot_path}"/*.csr
