#!/bin/bash

set -e

# ensure gosub is installed (this will recompile it only if necessary)
# go get github.com/vito/gosub
go install github.com/vito/gosub@latest

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd $HERE/../packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub/g'
        fi
      done
    } > spec.new

    mv spec.new spec
  )
}

## Create a sync_package line for each BOSH package in this release
## add a -app line or -test line to include a particular app or test
## along with all of its dependencies

sync_package policy-server \
  -app policy-server/cmd/policy-server \
  -app policy-server/cmd/policy-server-internal \
  -app policy-server/cmd/migrate-db &

sync_package bosh-dns-adapter \
  -app bosh-dns-adapter &

sync_package service-discovery-controller \
  -app service-discovery-controller &

sync_package performance-test-sd \
  -test test/performance-sd \
  -app github.com/onsi/ginkgo/ginkgo &

GOOS=linux sync_package runc-cni \
  -app garden-external-networker &

wait

(cd $HERE && git diff --name-only packages/*/spec)
