#!/bin/bash

set -e -x -u
cd $GOPATH

# ensure gosub is installed (this will recompile it only if necessary)
# go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -app github.com/cloudfoundry-incubator/guardian-cni-adapter/... \
    -app github.com/containernetworking/cni/plugins/main/bridge \
    -app github.com/containernetworking/cni/plugins/ipam/host-local \
    -app netman-cf-acceptance/example-apps/proxy \
    -app github.com/onsi/ginkgo/ginkgo \
    -app github.com/cloudfoundry-incubator/guardian-cni-adapter \
    -app github.com/containernetworking/cni/plugins/main/bridge \
    -app github.com/containernetworking/cni/plugins/ipam/host-local \
    -app github.com/containernetworking/cni/plugins/meta/flannel \
    -app github.com/coreos/flannel \
    -app github.com/rosenhouse/gosub &

  gosub list \
    -test acceptance \
    -test netman-cf-acceptance

} > /tmp/packages

cat /tmp/packages | xargs gosub sync
