#!/bin/bash

set -e -u -x

THIS_DIR=$(cd $(dirname $0) && pwd)
cd $THIS_DIR

export CONFIG=/tmp/test-config.json
export APPS_DIR=`pwd`/../src/example-apps

ENVIRONMENT_NAME="$1"

BBL_STATE_DIR="$HOME/workspace/cf-networking-deployments/environments/$ENVIRONMENT_NAME/bbl-state"
eval "$(bbl --state-dir "${BBL_STATE_DIR}" print-env)"

echo "
{
  \"api\": \"api.$ENVIRONMENT_NAME.c2c.cf-app.com\",
  \"admin_user\": \"admin\",
  \"admin_password\": \"{{admin-password}}\",
  \"admin_secret\": \"{{admin-secret}}\",
  \"apps_domain\": \"${ENVIRONMENT_NAME}.c2c.cf-app.com\",
  \"default_security_groups\": [ \"dns\", \"public_networks\" ],
  \"skip_experimental_dynamic_egress_tests\": false,
  \"skip_ssl_validation\": true,
  \"test_app_instances\": 2,
  \"test_applications\": 2,
  \"proxy_instances\": 1,
  \"proxy_applications\": 1,
  \"extra_listen_ports\": 2,
  \"prefix\":\"cf-networking-test-\"
}
" > ${CONFIG}

ADMIN_PASSWORD="$(credhub get -n "/bosh-${ENVIRONMENT_NAME}/cf/cf_admin_password" | bosh int --path /value -)"
sed -i -- "s/{{admin-password}}/${ADMIN_PASSWORD}/g" /tmp/test-config.json
ADMIN_SECRET=$(credhub get -n "/bosh-${ENVIRONMENT_NAME}/cf/uaa_admin_client_secret" | bosh int --path /value -)
sed -i -- "s/{{admin-secret}}/${ADMIN_SECRET}/g" /tmp/test-config.json

ginkgo -v ../src/test/acceptance
