#!/bin/bash

set -e -u -x

THIS_DIR=$(cd $(dirname $0) && pwd)
cd $THIS_DIR

export CONFIG=/tmp/test-config.json
export APPS_DIR=`pwd`/../src/example-apps

ENVIRONMENT_NAME="$1"
API_URL=$(smith -e $ENVIRONMENT_NAME read | jq .cf.api_url -r)
ADMIN_PASSWORD="$(credhub get -n "/bosh-${ENVIRONMENT_NAME}/cf/cf_admin_password" | bosh int --path /value -)"
cf auth admin ${ADMIN_PASSWORD}
APP_DOMAIN=$(cf curl /v2/domains | jq .resources[0].entity.name -r)
ADMIN_SECRET=$(credhub get -n "/bosh-${ENVIRONMENT_NAME}/cf/uaa_admin_client_secret" | bosh int --path /value -)

echo "
{
  \"api\": \"${API_URL}\",
  \"admin_user\": \"admin\",
  \"admin_password\": \"${ADMIN_PASSWORD}\",
  \"admin_secret\": \"${ADMIN_SECRET}\",
  \"apps_domain\": \"${APP_DOMAIN}\",
  \"default_security_groups\": [ \"dns\", \"public_networks\" ],
  \"skip_ssl_validation\": true,
  \"test_app_instances\": 2,
  \"test_applications\": 2,
  \"proxy_instances\": 1,
  \"proxy_applications\": 1,
  \"extra_listen_ports\": 2,
  \"prefix\":\"cf-networking-test-\"
}
" > ${CONFIG}


ginkgo -v ../src/test/acceptance-sd
