#!/bin/bash

set -e -u -x

THIS_DIR=$(cd $(dirname $0) && pwd)
cd $THIS_DIR

export CONFIG=/tmp/test-config.json
export APPS_DIR=`pwd`/../src/example-apps

ENVIRONMENT_NAME="$1"

echo "
{
  \"nats_url\": \"10.0.16.19\",
  \"nats_username\": \"nats\",
  \"nats_password\": \"{{nats_password}}\",
  \"nats_monitoring_port\": 8222,
  \"num_messages\": 10,
  \"num_publishers\": 10
}
" > ${CONFIG}

NATS_PASSWORD="$(credhub get -n "/bosh-${ENVIRONMENT_NAME}/cf/nats_password" | bosh int --path /value -)"
sed -i -- "s/{{nats_password}}/${NATS_PASSWORD}/g" /tmp/test-config.json

ginkgo -v ../src/code.cloudfoundry.org/test/performance-sd
