#!/bin/bash

set -e -u -x

cd cf-networking-release
export GOPATH=$PWD

declare -a serial_packages=(
  "src/policy-server/integration/timeouts"
  "src/policy-server/integration"
  "src/policy-server/store/migrations"
  "src/policy-server/store"
)

# smoke/perf/acceptance/scaling tests should be skipped
declare -a ignored_packages=(
  "src/test"
)

function loadIFB {
  set +e
    depmod $(uname -r)
    modprobe ifb
  set -e
}

function bootDB {
  db=$1

  if [ "$db" = "random" ]; then
    cointoss=$RANDOM
    set +e
    let "cointoss %= 2"
    set -e
    if [ "$cointoss" == "0" ]; then
      db="postgres"
    else
      db="mysql"
    fi
  fi

  if [ "$db" = "postgres" ]; then
    launchDB="(/docker-entrypoint.sh postgres &> /var/log/postgres-boot.log) &"
    testConnection="psql -h localhost -U postgres -c '\conninfo' &>/dev/null"
  elif [ "$db" = "mysql" ]  || [ "$db" = "mysql-5.6" ]; then
    launchDB="(MYSQL_ROOT_PASSWORD=password /entrypoint.sh mysqld &> /var/log/mysql-boot.log) &"
    testConnection="echo '\s;' | mysql -h 127.0.0.1 -u root --password='password' &>/dev/null"
  else
    echo "skipping database"
    return 0
  fi

  echo -n "booting $db"
  eval "$launchDB"
  for _ in $(seq 1 60); do
    set +e
    eval "${testConnection}"
    exitcode=$?
    set -e
    if [ ${exitcode} -eq 0 ]; then
      echo "connection established to $db"
      return 0
    fi
    echo -n "."
    sleep 1
  done
  echo "unable to connect to $db"
  exit 1
}

loadIFB
bootDB "${DB:-"notset"}"

# get all git submodule paths | print only the path without the extra info | cut the "package root" for go | deduplicate
declare -a git_modules=($(git config --file .gitmodules --get-regexp path | awk '{ print $2 }' | cut -d'/' -f1,2 | sort -u))

declare -a packages=($(find src -type f -name "*_test.go" | xargs -L 1 -I{} dirname {} | sort -u))

# filter out git_modules from packages
for i in "${git_modules[@]}"; do
  packages=(${packages[@]//*$i*})
done

# filter out serial_packages from packages
for i in "${serial_packages[@]}"; do
  packages=(${packages[@]//*$i*})
done

# filter out explicitly ignored packages
for i in "${ignored_packages[@]}"; do
  packages=(${packages[@]//*$i*})
done

if [ "${1:-""}" = "" ]; then
  for dir in "${packages[@]}"; do
    pushd "$dir"
      ginkgo -p --race -randomizeAllSpecs -randomizeSuites \
        -ldflags="-extldflags=-Wl,--allow-multiple-definition" \
        ${@:2}
    popd
  done
  for dir in "${serial_packages[@]}"; do
    pushd "$dir"
      ginkgo --race -randomizeAllSpecs -randomizeSuites -failFast \
        -ldflags="-extldflags=-Wl,--allow-multiple-definition" \
        ${@:2}
    popd
  done
else
  dir="${@: -1}"
  dir="${dir#./}"
  for package in "${serial_packages[@]}"; do
    if [[ "${dir##$package}" != "${dir}" ]]; then
      ginkgo --race -randomizeAllSpecs -randomizeSuites -failFast \
        -ldflags="-extldflags=-Wl,--allow-multiple-definition" \
        "${@}"
      exit $?
    fi
  done
  ginkgo -p --race -randomizeAllSpecs -randomizeSuites -failFast \
    -ldflags="-extldflags=-Wl,--allow-multiple-definition" \
    "${@}"
fi
