// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type Mounter struct {
	IdempotentlyMountStub        func(string, string) error
	idempotentlyMountMutex       sync.RWMutex
	idempotentlyMountArgsForCall []struct {
		arg1 string
		arg2 string
	}
	idempotentlyMountReturns struct {
		result1 error
	}
	idempotentlyMountReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveMountStub        func(string) error
	removeMountMutex       sync.RWMutex
	removeMountArgsForCall []struct {
		arg1 string
	}
	removeMountReturns struct {
		result1 error
	}
	removeMountReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Mounter) IdempotentlyMount(arg1 string, arg2 string) error {
	fake.idempotentlyMountMutex.Lock()
	ret, specificReturn := fake.idempotentlyMountReturnsOnCall[len(fake.idempotentlyMountArgsForCall)]
	fake.idempotentlyMountArgsForCall = append(fake.idempotentlyMountArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.IdempotentlyMountStub
	fakeReturns := fake.idempotentlyMountReturns
	fake.recordInvocation("IdempotentlyMount", []interface{}{arg1, arg2})
	fake.idempotentlyMountMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Mounter) IdempotentlyMountCallCount() int {
	fake.idempotentlyMountMutex.RLock()
	defer fake.idempotentlyMountMutex.RUnlock()
	return len(fake.idempotentlyMountArgsForCall)
}

func (fake *Mounter) IdempotentlyMountCalls(stub func(string, string) error) {
	fake.idempotentlyMountMutex.Lock()
	defer fake.idempotentlyMountMutex.Unlock()
	fake.IdempotentlyMountStub = stub
}

func (fake *Mounter) IdempotentlyMountArgsForCall(i int) (string, string) {
	fake.idempotentlyMountMutex.RLock()
	defer fake.idempotentlyMountMutex.RUnlock()
	argsForCall := fake.idempotentlyMountArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Mounter) IdempotentlyMountReturns(result1 error) {
	fake.idempotentlyMountMutex.Lock()
	defer fake.idempotentlyMountMutex.Unlock()
	fake.IdempotentlyMountStub = nil
	fake.idempotentlyMountReturns = struct {
		result1 error
	}{result1}
}

func (fake *Mounter) IdempotentlyMountReturnsOnCall(i int, result1 error) {
	fake.idempotentlyMountMutex.Lock()
	defer fake.idempotentlyMountMutex.Unlock()
	fake.IdempotentlyMountStub = nil
	if fake.idempotentlyMountReturnsOnCall == nil {
		fake.idempotentlyMountReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.idempotentlyMountReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Mounter) RemoveMount(arg1 string) error {
	fake.removeMountMutex.Lock()
	ret, specificReturn := fake.removeMountReturnsOnCall[len(fake.removeMountArgsForCall)]
	fake.removeMountArgsForCall = append(fake.removeMountArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RemoveMountStub
	fakeReturns := fake.removeMountReturns
	fake.recordInvocation("RemoveMount", []interface{}{arg1})
	fake.removeMountMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Mounter) RemoveMountCallCount() int {
	fake.removeMountMutex.RLock()
	defer fake.removeMountMutex.RUnlock()
	return len(fake.removeMountArgsForCall)
}

func (fake *Mounter) RemoveMountCalls(stub func(string) error) {
	fake.removeMountMutex.Lock()
	defer fake.removeMountMutex.Unlock()
	fake.RemoveMountStub = stub
}

func (fake *Mounter) RemoveMountArgsForCall(i int) string {
	fake.removeMountMutex.RLock()
	defer fake.removeMountMutex.RUnlock()
	argsForCall := fake.removeMountArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Mounter) RemoveMountReturns(result1 error) {
	fake.removeMountMutex.Lock()
	defer fake.removeMountMutex.Unlock()
	fake.RemoveMountStub = nil
	fake.removeMountReturns = struct {
		result1 error
	}{result1}
}

func (fake *Mounter) RemoveMountReturnsOnCall(i int, result1 error) {
	fake.removeMountMutex.Lock()
	defer fake.removeMountMutex.Unlock()
	fake.RemoveMountStub = nil
	if fake.removeMountReturnsOnCall == nil {
		fake.removeMountReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeMountReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Mounter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.idempotentlyMountMutex.RLock()
	defer fake.idempotentlyMountMutex.RUnlock()
	fake.removeMountMutex.RLock()
	defer fake.removeMountMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Mounter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
