#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export PIPELINE=${1:-cf-networking}
export TARGET=runtime-networking

fly -t "${TARGET}" sync
fly -t "${TARGET}" status || fly -t "${TARGET}" login -b

fly -t $TARGET \
  set-pipeline -p "${PIPELINE}" \
  -c "${DIR}/pipelines/${PIPELINE}.yml"
