#!/bin/bash

set -e -u
export PIPELINE=${1:-cf-networking}
export TARGET=net

fly -t $TARGET sync
fly -t $TARGET status || fly -t $TARGET login -b

fly -t $TARGET \
  set-pipeline -p $PIPELINE \
  -c $HOME/workspace/cf-networking-release/ci/pipelines/$PIPELINE.yml
