#!/bin/bash

set -e -u

environment_path="${PWD}/test-config/${TEST_CONFIG_DIR}"
export CONFIG=$environment_path/scaling-test-config.json
export APPS_DIR=${PWD}/cf-networking/src/example-apps

cd cf-networking
export GOPATH=$PWD

go run src/cf-pusher/cmd/cf-pusher/main.go --config "${CONFIG}"
