#!/bin/bash

set -euo pipefail

function cleanup() {
  pkill ssh || true
}

trap 'cleanup' EXIT

ROOT="$(cd "$(dirname $0)/../../../.." && pwd)"

source "${ROOT}/cf-deployment-concourse-tasks/shared-functions"
setup_bosh_env_vars

export CONFIG="${CONFIG:-"${ROOT}/test-config/perf-config.json"}"
export RELEASE_DIR=$PWD/cf-networking

BIN_DIR="${RELEASE_DIR}/bin"
export PATH="${BIN_DIR}":$PATH

pushd ${RELEASE_DIR}/src/code.cloudfoundry.org
  go build -o "${BIN_DIR}/ginkgo" github.com/onsi/ginkgo/ginkgo
popd

pushd ${RELEASE_DIR}/src/code.cloudfoundry.org/test/performance-sd
   ginkgo -race deploy/
   bosh -d performance run-errand performance-test-sd --keep-alive
   bosh -n -d performance delete-deployment
popd
