#!/bin/bash

set -euo pipefail

function cleanup() {
  pkill ssh || true
}

trap 'cleanup' EXIT

ROOT="$(cd "$(dirname $0)/../../../.." && pwd)"

source "${ROOT}/cf-deployment-concourse-tasks/shared-functions"
setup_bosh_env_vars

export GOPATH=$PWD/cf-networking
export PATH="${GOPATH}/bin":$PATH
export CONFIG="${CONFIG:-"${ROOT}/test-config/perf-config.json"}"

go get -u github.com/onsi/ginkgo/ginkgo

export GO111MODULE="auto"
pushd cf-networking/src/test/performance-sd
   ginkgo -race deploy/
   bosh -d performance run-errand performance-test-sd --keep-alive
   bosh -n -d performance delete-deployment
popd
