#!/bin/sh
set -e -x

export PATH=$GOPATH/bin:$PATH

DEVELOP=$PWD/cf-networking-dev

git clone ./cf-networking-master ./release-merged

cd release-merged

git remote add local $DEVELOP

git fetch local
git checkout local/develop

git config --global user.email "container-networking+ci@pivotal.io"
git config --global user.name "Container Networking Bot"

git merge --no-edit release # new default branch is now release
