#!/bin/bash
set -e -x -u -o pipefail

indir=./bbl-state
outdir=./updated-bbl-state
git clone "${indir}" "${outdir}"

dest_dir="${outdir}/environments/${ENVIRONMENT}/bbl-state/terraform/"
mkdir -p "${dest_dir}"

cp "${PWD}/cf-networking-release-ci/ci/tasks/bbl-full-parent-dns_override.tf" "${dest_dir}"

function set_git_config() {
  if [ -z "${GIT_COMMIT_USERNAME}" ]; then
    GIT_COMMIT_USERNAME="CI Bot"
  fi

  if [ -z "${GIT_COMMIT_EMAIL}" ]; then
    GIT_COMMIT_EMAIL="container-networking+ci@pivotal.io"
  fi

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

function commit_dns_tf {
  local root_dir
  root_dir="${1}"
  local commit_message
  commit_message="${2}"

  pushd "${root_dir}/${outdir}/environments/${ENVIRONMENT}"
    if [[ -n $(git status --porcelain) ]]; then
    set_git_config
    git add bbl-state/terraform
    git commit -m "${commit_message}"
  fi
}

commit_dns_tf "${PWD}" "Adding dns terraform templates"
