#!/bin/sh

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="netman-certs"
mkdir -p ${depot_path}

# CA to distribute to netman clients and servers
certstrap --depot-path ${depot_path} init --passphrase '' --common-name netmanCA
mv -f ${depot_path}/netmanCA.crt ${depot_path}/netman-ca.crt
mv -f ${depot_path}/netmanCA.key ${depot_path}/netman-ca.key

# Server certificate for the policy server
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name policy-server.service.cf.internal --ip '127.0.0.1' --domain 'policy-server.service.cf.internal'
certstrap --depot-path ${depot_path} sign policy-server.service.cf.internal --CA netman-ca
mv -f ${depot_path}/policy-server.service.cf.internal.key ${depot_path}/server.key
mv -f ${depot_path}/policy-server.service.cf.internal.csr ${depot_path}/server.csr
mv -f ${depot_path}/policy-server.service.cf.internal.crt ${depot_path}/server.crt

# Client certificate for the policy agents
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name 'clientName'
certstrap --depot-path ${depot_path} sign clientName --CA netman-ca
mv -f ${depot_path}/clientName.key ${depot_path}/client.key
mv -f ${depot_path}/clientName.csr ${depot_path}/client.csr
mv -f ${depot_path}/clientName.crt ${depot_path}/client.crt
