#!/usr/bin/env bash

set -eu

ROOT="$(cd "$(dirname $0)/../../../.." && pwd)"
. "${ROOT}/cf-networking-release-ci/ci/tasks/sli-setup/shared-sli-functions.sh"

APP_URL="${SLI_APP_NAME}.$(get_var_from_json apps_domain)"


function dig_app_until_resolved() {
    until $(curl --output /dev/null --silent --head --fail "${APP_URL}"/dig/"${SLI_APP_NAME}".apps.internal); do
        printf '.'
    done
}

function report_timing_to_datadog() {
    time_to_resolve="${1}"

    curl -f -X POST -H "Content-type: application/json" \
    -d "{ \"series\" :
           [{\"metric\":\"cf_networking_sli.MapRouteTime\",
            \"points\":[[$(date +%s), ${time_to_resolve}]],
            \"type\":\"gauge\",
            \"tags\":[\"deployment:${DATADOG_ENVIRONMENT_TAG}\"]
          }]
        }" \
      "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}"
}

function report_status_to_datadog() {
    status=0
    if [[ ${time_to_resolve} -le 5000 ]]; then
      status=1
    fi

    curl -f -X POST -H "Content-type: application/json" \
    -d "{ \"series\" :
           [{\"metric\":\"cf_networking_sli.MapRouteStatus\",
            \"points\":[[$(date +%s), ${status}]],
            \"type\":\"gauge\",
            \"tags\":[\"deployment:${DATADOG_ENVIRONMENT_TAG}\"]
          }]
        }" \
      "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}"
}

function main() {
    cf_login
    cf_target
    map_internal_route

    start=$(now_in_ms)
    dig_app_until_resolved
    end=$(now_in_ms)

    time_to_resolve=$(( $end - $start ))
    printf "Time to resolve route: ${time_to_resolve}\n"
    report_timing_to_datadog "${time_to_resolve}"
    report_status_to_datadog

    unmap_internal_route
}

main
